language: clojure

lein: lein2

script: lein2 test

# May need other tools later
before_install:
  - sudo apt-get update
  - sudo apt-get install verilog

branches:
  only:
    - master
    - new-modules
